apiVersion: v1
kind: Pod
metadata:
  name: station-rest
  labels:
    app: web
spec:
  containers:
    - image: gcr.io/bike-rental-system/station-rest
      name: station-rest
      ports:
        - containerPort: 8080
      env:
        - name: CASSANDRA_HOST
          value: indb2
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: bike-rental-system-d3bc3066fbe8.json
    
